// GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
// Source of truth: src/app/globals.css
export interface Primitive { name: string; value: string; hex: string | null; note: string | null }
export interface Token {
  /** null when only Product defines the token (e.g. --sidebar). */
  name: string; value: string | null; ref: string | null; hex: string | null; note: string | null;
  /** The same token under .theme-product. null when Product cannot resolve it (Editorial-only, e.g. the hero overlays). */
  productValue: string | null; productRef: string | null; productHex: string | null;
  /** True when the two densities resolve to different colours. */
  differs: boolean;
}

/** Tier 1 — the raw ramps in :root. No meaning attached. */
export const PRIMITIVES: Primitive[] = [
  {
    "name": "--gray-50",
    "value": "0 0% 94.9%",
    "hex": "#F2F2F2",
    "note": "#F2F2F2"
  },
  {
    "name": "--gray-100",
    "value": "0 0% 92.2%",
    "hex": "#EBEBEB",
    "note": "#EBEBEB"
  },
  {
    "name": "--gray-200",
    "value": "0 0% 83.1%",
    "hex": "#D4D4D4",
    "note": "#D4D4D4"
  },
  {
    "name": "--gray-300",
    "value": "0 0% 78.8%",
    "hex": "#C9C9C9",
    "note": "#C9C9C9"
  },
  {
    "name": "--gray-400",
    "value": "0 0% 65.9%",
    "hex": "#A8A8A8",
    "note": "#A8A8A8"
  },
  {
    "name": "--gray-500",
    "value": "0 0% 56.1%",
    "hex": "#8F8F8F",
    "note": "#8F8F8F"
  },
  {
    "name": "--gray-600",
    "value": "0 0% 49%",
    "hex": "#7D7D7D",
    "note": "#7D7D7D"
  },
  {
    "name": "--gray-700",
    "value": "0 0% 40%",
    "hex": "#666666",
    "note": "#666666"
  },
  {
    "name": "--gray-800",
    "value": "0 0% 30.2%",
    "hex": "#4D4D4D",
    "note": "#4D4D4D"
  },
  {
    "name": "--gray-900",
    "value": "0 0% 9%",
    "hex": "#171717",
    "note": "#171717"
  },
  {
    "name": "--red-50",
    "value": "7.5 57.1% 97.3%",
    "hex": "#FCF5F4",
    "note": "#FCF5F4"
  },
  {
    "name": "--red-100",
    "value": "6 62.5% 93.7%",
    "hex": "#F9E7E5",
    "note": "#F9E7E5"
  },
  {
    "name": "--red-200",
    "value": "4.7 70.4% 89.4%",
    "hex": "#F7D4D1",
    "note": "#F7D4D1"
  },
  {
    "name": "--red-300",
    "value": "3.5 81% 83.5%",
    "hex": "#F7B7B3",
    "note": "#F7B7B3"
  },
  {
    "name": "--red-400",
    "value": "0 100% 68%",
    "hex": "#FF5C5C",
    "note": "#FF5C5C"
  },
  {
    "name": "--red-500",
    "value": "0 87.8% 52%",
    "hex": "#F01919",
    "note": "#F01919"
  },
  {
    "name": "--red-600",
    "value": "0 95.1% 40%",
    "hex": "#C70505",
    "note": "#C70505"
  },
  {
    "name": "--red-700",
    "value": "0 89.9% 35.1%",
    "hex": "#AA0909",
    "note": "#AA0909"
  },
  {
    "name": "--red-800",
    "value": "358 88.2% 26.7%",
    "hex": "#80080C",
    "note": "#80080C"
  },
  {
    "name": "--red-900",
    "value": "355.7 83.1% 16.3%",
    "hex": "#4C070C",
    "note": "#4C070C"
  },
  {
    "name": "--coral-50",
    "value": "0 57.1% 97.3%",
    "hex": "#FCF4F4",
    "note": "#FCF4F4"
  },
  {
    "name": "--coral-100",
    "value": "5.7 67.7% 93.9%",
    "hex": "#FAE7E5",
    "note": "#FAE7E5"
  },
  {
    "name": "--coral-200",
    "value": "3.1 73.6% 89.6%",
    "hex": "#F8D3D1",
    "note": "#F8D3D1"
  },
  {
    "name": "--coral-300",
    "value": "1 75.9% 83.7%",
    "hex": "#F5B7B6",
    "note": "#F5B7B6"
  },
  {
    "name": "--coral-400",
    "value": "359.4 76.2% 72%",
    "hex": "#EE8182",
    "note": "#EE8182"
  },
  {
    "name": "--coral-500",
    "value": "358.1 75.1% 59%",
    "hex": "#E5484D",
    "note": "#E5484D"
  },
  {
    "name": "--coral-600",
    "value": "0 72% 51%",
    "hex": "#DC2828",
    "note": "#DC2828"
  },
  {
    "name": "--coral-700",
    "value": "357.8 68.2% 39.4%",
    "hex": "#A92025",
    "note": "#A92025"
  },
  {
    "name": "--coral-800",
    "value": "356.2 64% 29.4%",
    "hex": "#7B1B21",
    "note": "#7B1B21"
  },
  {
    "name": "--coral-900",
    "value": "354.2 57.8% 17.6%",
    "hex": "#471318",
    "note": "#471318"
  },
  {
    "name": "--green-50",
    "value": "144 45.5% 95.7%",
    "hex": "#EFF9F3",
    "note": "#EFF9F3"
  },
  {
    "name": "--green-100",
    "value": "146 53.6% 89%",
    "hex": "#D4F2E1",
    "note": "#D4F2E1"
  },
  {
    "name": "--green-200",
    "value": "145.3 58.2% 78.4%",
    "hex": "#A8E8C3",
    "note": "#A8E8C3"
  },
  {
    "name": "--green-300",
    "value": "145.3 64% 60.8%",
    "hex": "#5BDB91",
    "note": "#5BDB91"
  },
  {
    "name": "--green-400",
    "value": "142.1 71.2% 44.9%",
    "hex": "#21C45D",
    "note": "#21C45D"
  },
  {
    "name": "--green-500",
    "value": "141.9 74.1% 36.3%",
    "hex": "#18A14A",
    "note": "#18A14A"
  },
  {
    "name": "--green-600",
    "value": "142.1 71.6% 29%",
    "hex": "#157F3C",
    "note": "#157F3C"
  },
  {
    "name": "--green-700",
    "value": "145.2 70.4% 22.5%",
    "hex": "#116233",
    "note": "#116233"
  },
  {
    "name": "--green-800",
    "value": "148.9 66.7% 16.5%",
    "hex": "#0E4629",
    "note": "#0E4629"
  },
  {
    "name": "--green-900",
    "value": "151.9 59.3% 10.6%",
    "hex": "#0B2B1C",
    "note": "#0B2B1C"
  },
  {
    "name": "--amber-50",
    "value": "38.4 100% 95.1%",
    "hex": "#FFF6E6",
    "note": "#FFF6E6"
  },
  {
    "name": "--amber-100",
    "value": "43.9 100% 92%",
    "hex": "#FFF4D6",
    "note": "#FFF4D6"
  },
  {
    "name": "--amber-200",
    "value": "42.9 96.1% 90%",
    "hex": "#FEF0CD",
    "note": "#FEF0CD"
  },
  {
    "name": "--amber-300",
    "value": "41.8 100% 78%",
    "hex": "#FFDD8F",
    "note": "#FFDD8F"
  },
  {
    "name": "--amber-400",
    "value": "38.1 100% 71%",
    "hex": "#FFC96B",
    "note": "#FFC96B"
  },
  {
    "name": "--amber-500",
    "value": "44.9 96.9% 50%",
    "hex": "#FBBD04",
    "note": "#FBBD04"
  },
  {
    "name": "--amber-600",
    "value": "38.9 100% 57.1%",
    "hex": "#FFB224",
    "note": "#FFB224"
  },
  {
    "name": "--amber-700",
    "value": "35 100% 52%",
    "hex": "#FF990A",
    "note": "#FF990A"
  },
  {
    "name": "--amber-800",
    "value": "30.2 100% 32%",
    "hex": "#A35200",
    "note": "#A35200"
  },
  {
    "name": "--amber-900",
    "value": "20 79.3% 17.1%",
    "hex": "#4E2009",
    "note": "#4E2009"
  },
  {
    "name": "--white",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": "#FFFFFF"
  },
  {
    "name": "--slate-50",
    "value": "210 20% 98%",
    "hex": "#F9FAFB",
    "note": "#F9FAFB"
  },
  {
    "name": "--whatsapp-brand",
    "value": "142.4 70.2% 48.6%",
    "hex": "#25D366",
    "note": "#25D366"
  },
  {
    "name": "--blue-300",
    "value": "210.7 100% 77.8%",
    "hex": "#8EC5FF",
    "note": "#8EC5FF, 1.81:1 on white"
  },
  {
    "name": "--blue-500",
    "value": "216.3 100% 58.4%",
    "hex": "#2B7FFF",
    "note": "#2B7FFF, 3.76:1"
  },
  {
    "name": "--blue-600",
    "value": "221.3 97.1% 53.5%",
    "hex": "#155DFC",
    "note": "#155DFC, 5.26:1"
  },
  {
    "name": "--blue-700",
    "value": "225.3 84.1% 49%",
    "hex": "#1447E6",
    "note": "#1447E6, 6.82:1"
  },
  {
    "name": "--blue-800",
    "value": "226.8 76.1% 41%",
    "hex": "#193CB8",
    "note": "#193CB8, 8.84:1"
  },
  {
    "name": "--zinc-50",
    "value": "0 0% 98%",
    "hex": "#FAFAFA",
    "note": "#FAFAFA"
  },
  {
    "name": "--zinc-100",
    "value": "240 4.8% 95.9%",
    "hex": "#F4F4F5",
    "note": "#F4F4F5"
  },
  {
    "name": "--zinc-200",
    "value": "240 5.9% 90%",
    "hex": "#E4E4E7",
    "note": "#E4E4E7"
  },
  {
    "name": "--zinc-300",
    "value": "240 4.9% 83.9%",
    "hex": "#D4D4D8",
    "note": "#D4D4D8"
  },
  {
    "name": "--zinc-500",
    "value": "240 4.2% 46.3%",
    "hex": "#71717B",
    "note": "#71717B"
  },
  {
    "name": "--zinc-600",
    "value": "240 5.7% 34.1%",
    "hex": "#52525C",
    "note": "#52525C"
  },
  {
    "name": "--zinc-800",
    "value": "240 3.7% 15.9%",
    "hex": "#27272A",
    "note": "#27272A"
  },
  {
    "name": "--zinc-900",
    "value": "240 5.9% 10%",
    "hex": "#18181B",
    "note": "#18181B"
  },
  {
    "name": "--zinc-950",
    "value": "240 10% 3.9%",
    "hex": "#09090B",
    "note": "#09090B"
  }
];

/** Tier 2 — the semantic layer in both densities. `ref` / `productRef` name the primitive each borrows. */
export const THEME_TOKENS: Token[] = [
  {
    "name": "--background",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--white)",
    "productRef": "--white",
    "productHex": "#FFFFFF",
    "differs": false
  },
  {
    "name": "--foreground",
    "value": "var(--gray-900)",
    "ref": "--gray-900",
    "hex": "#171717",
    "note": "#171717, matches the DS --primary",
    "productValue": "var(--zinc-950)",
    "productRef": "--zinc-950",
    "productHex": "#09090B",
    "differs": true
  },
  {
    "name": "--card",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--white)",
    "productRef": "--white",
    "productHex": "#FFFFFF",
    "differs": false
  },
  {
    "name": "--card-foreground",
    "value": "var(--gray-900)",
    "ref": "--gray-900",
    "hex": "#171717",
    "note": null,
    "productValue": "var(--zinc-950)",
    "productRef": "--zinc-950",
    "productHex": "#09090B",
    "differs": true
  },
  {
    "name": "--secondary",
    "value": "var(--slate-50)",
    "ref": "--slate-50",
    "hex": "#F9FAFB",
    "note": "#F9FAFB, cool off-white, not a pure grey",
    "productValue": "var(--zinc-100)",
    "productRef": "--zinc-100",
    "productHex": "#F4F4F5",
    "differs": true
  },
  {
    "name": "--secondary-foreground",
    "value": "var(--gray-900)",
    "ref": "--gray-900",
    "hex": "#171717",
    "note": null,
    "productValue": "var(--zinc-900)",
    "productRef": "--zinc-900",
    "productHex": "#18181B",
    "differs": true
  },
  {
    "name": "--muted",
    "value": "var(--slate-50)",
    "ref": "--slate-50",
    "hex": "#F9FAFB",
    "note": null,
    "productValue": "var(--zinc-100)",
    "productRef": "--zinc-100",
    "productHex": "#F4F4F5",
    "differs": true
  },
  {
    "name": "--muted-foreground",
    "value": "var(--gray-700)",
    "ref": "--gray-700",
    "hex": "#666666",
    "note": "#666666, matches the DS --secondary",
    "productValue": "var(--zinc-500)",
    "productRef": "--zinc-500",
    "productHex": "#71717B",
    "differs": true
  },
  {
    "name": "--border",
    "value": "var(--gray-100)",
    "ref": "--gray-100",
    "hex": "#EBEBEB",
    "note": "#EBEBEB",
    "productValue": "var(--zinc-200)",
    "productRef": "--zinc-200",
    "productHex": "#E4E4E7",
    "differs": true
  },
  {
    "name": "--input",
    "value": "var(--gray-100)",
    "ref": "--gray-100",
    "hex": "#EBEBEB",
    "note": null,
    "productValue": "var(--zinc-200)",
    "productRef": "--zinc-200",
    "productHex": "#E4E4E7",
    "differs": true
  },
  {
    "name": "--radius",
    "value": "0.75rem",
    "ref": null,
    "hex": null,
    "note": null,
    "productValue": "0.625rem",
    "productRef": null,
    "productHex": null,
    "differs": true
  },
  {
    "name": "--primary",
    "value": "var(--red-600)",
    "ref": "--red-600",
    "hex": "#C70505",
    "note": "#C70505, button fill, eyebrow labels",
    "productValue": "var(--zinc-900)",
    "productRef": "--zinc-900",
    "productHex": "#18181B",
    "differs": true
  },
  {
    "name": "--primary-foreground",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--white)",
    "productRef": "--white",
    "productHex": "#FFFFFF",
    "differs": false
  },
  {
    "name": "--accent",
    "value": "var(--red-600)",
    "ref": "--red-600",
    "hex": "#C70505",
    "note": null,
    "productValue": "var(--zinc-100)",
    "productRef": "--zinc-100",
    "productHex": "#F4F4F5",
    "differs": true
  },
  {
    "name": "--accent-foreground",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--zinc-900)",
    "productRef": "--zinc-900",
    "productHex": "#18181B",
    "differs": true
  },
  {
    "name": "--brand-hover",
    "value": "var(--red-700)",
    "ref": "--red-700",
    "hex": "#AA0909",
    "note": "#9E0404, darkens on hover (from the DS)",
    "productValue": "var(--zinc-800)",
    "productRef": "--zinc-800",
    "productHex": "#27272A",
    "differs": true
  },
  {
    "name": "--brand-icon",
    "value": "var(--coral-500)",
    "ref": "--coral-500",
    "hex": "#E5484D",
    "note": "#E5484D, card icon glyphs",
    "productValue": "var(--zinc-600)",
    "productRef": "--zinc-600",
    "productHex": "#52525C",
    "differs": true
  },
  {
    "name": "--brand-soft",
    "value": "var(--red-400)",
    "ref": "--red-400",
    "hex": "#FF5C5C",
    "note": "#FF5A5A, decorative borders/glows ONLY",
    "productValue": "var(--zinc-200)",
    "productRef": "--zinc-200",
    "productHex": "#E4E4E7",
    "differs": true
  },
  {
    "name": "--brand-deep",
    "value": "var(--red-700)",
    "ref": "--red-700",
    "hex": "#AA0909",
    "note": null,
    "productValue": "var(--zinc-800)",
    "productRef": "--zinc-800",
    "productHex": "#27272A",
    "differs": true
  },
  {
    "name": "--selection",
    "value": "var(--gray-900)",
    "ref": "--gray-900",
    "hex": "#171717",
    "note": null,
    "productValue": "var(--zinc-900)",
    "productRef": "--zinc-900",
    "productHex": "#18181B",
    "differs": true
  },
  {
    "name": "--selection-border",
    "value": "var(--gray-800)",
    "ref": "--gray-800",
    "hex": "#4D4D4D",
    "note": "#404040, input border on focus",
    "productValue": "var(--zinc-800)",
    "productRef": "--zinc-800",
    "productHex": "#27272A",
    "differs": true
  },
  {
    "name": "--field",
    "value": "var(--gray-200)",
    "ref": "--gray-200",
    "hex": "#D4D4D4",
    "note": "#D4D4D4, input/option border at rest",
    "productValue": "var(--zinc-300)",
    "productRef": "--zinc-300",
    "productHex": "#D4D4D8",
    "differs": true
  },
  {
    "name": "--field-hover",
    "value": "var(--gray-600)",
    "ref": "--gray-600",
    "hex": "#7D7D7D",
    "note": "#737373, border on hover",
    "productValue": "var(--zinc-500)",
    "productRef": "--zinc-500",
    "productHex": "#71717B",
    "differs": true
  },
  {
    "name": "--ring",
    "value": "var(--gray-900)",
    "ref": "--gray-900",
    "hex": "#171717",
    "note": "focus ring = selection, not red",
    "productValue": "var(--zinc-900)",
    "productRef": "--zinc-900",
    "productHex": "#18181B",
    "differs": true
  },
  {
    "name": "--error",
    "value": "var(--coral-600)",
    "ref": "--coral-600",
    "hex": "#DC2828",
    "note": "#DC2626, 4.83:1 on white ✓ AA",
    "productValue": "var(--coral-600)",
    "productRef": "--coral-600",
    "productHex": "#DC2828",
    "differs": false
  },
  {
    "name": "--error-foreground",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--white)",
    "productRef": "--white",
    "productHex": "#FFFFFF",
    "differs": false
  },
  {
    "name": "--destructive",
    "value": "var(--coral-600)",
    "ref": "--coral-600",
    "hex": "#DC2828",
    "note": "alias so shadcn primitives inherit it",
    "productValue": "var(--coral-600)",
    "productRef": "--coral-600",
    "productHex": "#DC2828",
    "differs": false
  },
  {
    "name": "--destructive-foreground",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--white)",
    "productRef": "--white",
    "productHex": "#FFFFFF",
    "differs": false
  },
  {
    "name": "--success",
    "value": "var(--green-600)",
    "ref": "--green-600",
    "hex": "#157F3C",
    "note": "#15803D, 4.86:1 on white ✓ AA",
    "productValue": "var(--green-600)",
    "productRef": "--green-600",
    "productHex": "#157F3C",
    "differs": false
  },
  {
    "name": "--success-foreground",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--white)",
    "productRef": "--white",
    "productHex": "#FFFFFF",
    "differs": false
  },
  {
    "name": "--success-bright",
    "value": "var(--green-400)",
    "ref": "--green-400",
    "hex": "#21C45D",
    "note": "#22C55E, for the dark hero only",
    "productValue": "var(--green-400)",
    "productRef": "--green-400",
    "productHex": "#21C45D",
    "differs": false
  },
  {
    "name": "--gold",
    "value": "var(--amber-500)",
    "ref": "--amber-500",
    "hex": "#FBBD04",
    "note": "#FBBC04, review stars",
    "productValue": "var(--amber-500)",
    "productRef": "--amber-500",
    "productHex": "#FBBD04",
    "differs": false
  },
  {
    "name": "--whatsapp",
    "value": "var(--whatsapp-brand)",
    "ref": "--whatsapp-brand",
    "hex": "#25D366",
    "note": "#25D366",
    "productValue": "var(--whatsapp-brand)",
    "productRef": "--whatsapp-brand",
    "productHex": "#25D366",
    "differs": false
  },
  {
    "name": "--hero-overlay",
    "value": "linear-gradient(to bottom, rgba(10, 25, 41, 0.6), rgba(13, 27, 42, 0.7), rgba(0, 0, 0, 0.85))",
    "ref": null,
    "hex": null,
    "note": null,
    "productValue": null,
    "productRef": null,
    "productHex": null,
    "differs": false
  },
  {
    "name": "--hero-overlay-md",
    "value": "linear-gradient(to bottom, rgba(10, 25, 41, 0.55), rgba(13, 27, 42, 0.65), rgba(0, 0, 0, 0.82))",
    "ref": null,
    "hex": null,
    "note": null,
    "productValue": null,
    "productRef": null,
    "productHex": null,
    "differs": false
  },
  {
    "name": "--eq-img-grad",
    "value": "radial-gradient(90% 90% at 50% 20%, #f2f3f6, #e7e9ef)",
    "ref": null,
    "hex": null,
    "note": null,
    "productValue": null,
    "productRef": null,
    "productHex": null,
    "differs": false
  },
  {
    "name": "--before-grad",
    "value": "linear-gradient(160deg, #eef0f4, #e2e5ec)",
    "ref": null,
    "hex": null,
    "note": null,
    "productValue": null,
    "productRef": null,
    "productHex": null,
    "differs": false
  },
  {
    "name": "--ease-out",
    "value": "cubic-bezier(0.16, 1, 0.3, 1)",
    "ref": null,
    "hex": null,
    "note": null,
    "productValue": null,
    "productRef": null,
    "productHex": null,
    "differs": false
  },
  {
    "name": "--warning",
    "value": "var(--amber-800)",
    "ref": "--amber-800",
    "hex": "#A35200",
    "note": null,
    "productValue": "var(--amber-800)",
    "productRef": "--amber-800",
    "productHex": "#A35200",
    "differs": false
  },
  {
    "name": "--warning-foreground",
    "value": "var(--white)",
    "ref": "--white",
    "hex": "#FFFFFF",
    "note": null,
    "productValue": "var(--white)",
    "productRef": "--white",
    "productHex": "#FFFFFF",
    "differs": false
  },
  {
    "name": "--chart-1",
    "value": "var(--blue-300)",
    "ref": "--blue-300",
    "hex": "#8EC5FF",
    "note": null,
    "productValue": "var(--blue-300)",
    "productRef": "--blue-300",
    "productHex": "#8EC5FF",
    "differs": false
  },
  {
    "name": "--chart-2",
    "value": "var(--blue-500)",
    "ref": "--blue-500",
    "hex": "#2B7FFF",
    "note": null,
    "productValue": "var(--blue-500)",
    "productRef": "--blue-500",
    "productHex": "#2B7FFF",
    "differs": false
  },
  {
    "name": "--chart-3",
    "value": "var(--blue-600)",
    "ref": "--blue-600",
    "hex": "#155DFC",
    "note": null,
    "productValue": "var(--blue-600)",
    "productRef": "--blue-600",
    "productHex": "#155DFC",
    "differs": false
  },
  {
    "name": "--chart-4",
    "value": "var(--blue-700)",
    "ref": "--blue-700",
    "hex": "#1447E6",
    "note": null,
    "productValue": "var(--blue-700)",
    "productRef": "--blue-700",
    "productHex": "#1447E6",
    "differs": false
  },
  {
    "name": "--chart-5",
    "value": "var(--blue-800)",
    "ref": "--blue-800",
    "hex": "#193CB8",
    "note": null,
    "productValue": "var(--blue-800)",
    "productRef": "--blue-800",
    "productHex": "#193CB8",
    "differs": false
  },
  {
    "name": "--chart-accent",
    "value": "var(--gray-900)",
    "ref": "--gray-900",
    "hex": "#171717",
    "note": "the series stay blue; only the neutrals move to zinc",
    "productValue": "var(--zinc-900)",
    "productRef": "--zinc-900",
    "productHex": "#18181B",
    "differs": true
  },
  {
    "name": "--chart-grid",
    "value": "var(--gray-100)",
    "ref": "--gray-100",
    "hex": "#EBEBEB",
    "note": null,
    "productValue": "var(--zinc-200)",
    "productRef": "--zinc-200",
    "productHex": "#E4E4E7",
    "differs": true
  },
  {
    "name": "--sidebar",
    "value": null,
    "ref": null,
    "hex": null,
    "note": "the nav column, one step off the canvas",
    "productValue": "var(--zinc-50)",
    "productRef": "--zinc-50",
    "productHex": "#FAFAFA",
    "differs": true
  }
];

export interface ScaleRow { name: string; editorial: string; product: string; differs: boolean }
export interface Scale { family: string; rows: ScaleRow[] }

/** Tier 2 — the scalar tokens, side by side in both densities. */
export const SCALES: Scale[] = [
  {
    "family": "Type scale",
    "rows": [
      {
        "name": "--text-micro",
        "editorial": "10.5px",
        "product": "10px",
        "differs": true
      },
      {
        "name": "--text-label",
        "editorial": "12px",
        "product": "11px",
        "differs": true
      },
      {
        "name": "--text-caption",
        "editorial": "13px",
        "product": "12px",
        "differs": true
      },
      {
        "name": "--text-body-sm",
        "editorial": "14px",
        "product": "13px",
        "differs": true
      },
      {
        "name": "--text-body",
        "editorial": "16px",
        "product": "14px",
        "differs": true
      },
      {
        "name": "--text-entry",
        "editorial": "16px",
        "product": "16px",
        "differs": false
      },
      {
        "name": "--text-lead",
        "editorial": "18px",
        "product": "16px",
        "differs": true
      },
      {
        "name": "--text-title",
        "editorial": "20px",
        "product": "18px",
        "differs": true
      },
      {
        "name": "--text-heading",
        "editorial": "28px",
        "product": "24px",
        "differs": true
      },
      {
        "name": "--text-metric",
        "editorial": "28px",
        "product": "24px",
        "differs": true
      }
    ]
  },
  {
    "family": "Button voice",
    "rows": [
      {
        "name": "--button-size",
        "editorial": "12px",
        "product": "13px",
        "differs": true
      },
      {
        "name": "--button-weight",
        "editorial": "700",
        "product": "600",
        "differs": true
      },
      {
        "name": "--button-case",
        "editorial": "uppercase",
        "product": "none",
        "differs": true
      },
      {
        "name": "--button-tracking",
        "editorial": "-0.2px",
        "product": "0",
        "differs": true
      }
    ]
  },
  {
    "family": "Line height",
    "rows": [
      {
        "name": "--leading-body",
        "editorial": "1.5",
        "product": "1.42",
        "differs": true
      }
    ]
  },
  {
    "family": "Control height",
    "rows": [
      {
        "name": "--control-sm",
        "editorial": "36px",
        "product": "36px",
        "differs": false
      },
      {
        "name": "--control-aux",
        "editorial": "40px",
        "product": "40px",
        "differs": false
      },
      {
        "name": "--control",
        "editorial": "48px",
        "product": "44px",
        "differs": true
      },
      {
        "name": "--control-lg",
        "editorial": "56px",
        "product": "48px",
        "differs": true
      }
    ]
  },
  {
    "family": "Border width",
    "rows": [
      {
        "name": "--border-field",
        "editorial": "1.5px",
        "product": "1.5px",
        "differs": false
      },
      {
        "name": "--border-control",
        "editorial": "2px",
        "product": "2px",
        "differs": false
      }
    ]
  },
  {
    "family": "Motion",
    "rows": [
      {
        "name": "--motion-quick",
        "editorial": "200ms",
        "product": "200ms",
        "differs": false
      },
      {
        "name": "--motion-card",
        "editorial": "450ms",
        "product": "450ms",
        "differs": false
      },
      {
        "name": "--motion-panel",
        "editorial": "550ms",
        "product": "550ms",
        "differs": false
      }
    ]
  },
  {
    "family": "Radius",
    "rows": [
      {
        "name": "--radius",
        "editorial": "0.75rem",
        "product": "0.625rem",
        "differs": true
      }
    ]
  }
];
