// GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
// Source of truth: src/app/globals.css → .theme-funnel
export interface Token { name: string; value: string; hex: string | null; note: string | null }
export const THEME_TOKENS: Token[] = [
  {
    "name": "--background",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": null
  },
  {
    "name": "--foreground",
    "value": "0 0% 9%",
    "hex": "#171717",
    "note": "#171717 — matches the DS --primary"
  },
  {
    "name": "--card",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": null
  },
  {
    "name": "--card-foreground",
    "value": "0 0% 9%",
    "hex": "#171717",
    "note": null
  },
  {
    "name": "--secondary",
    "value": "210 20% 98%",
    "hex": "#F9FAFB",
    "note": "#F9FAFB — cool off-white, not a pure grey"
  },
  {
    "name": "--secondary-foreground",
    "value": "0 0% 9%",
    "hex": "#171717",
    "note": null
  },
  {
    "name": "--muted",
    "value": "210 20% 98%",
    "hex": "#F9FAFB",
    "note": null
  },
  {
    "name": "--muted-foreground",
    "value": "0 0% 40%",
    "hex": "#666666",
    "note": "#666666 — matches the DS --secondary"
  },
  {
    "name": "--border",
    "value": "0 0% 92%",
    "hex": "#EBEBEB",
    "note": "#EBEBEB"
  },
  {
    "name": "--input",
    "value": "0 0% 92%",
    "hex": "#EBEBEB",
    "note": null
  },
  {
    "name": "--radius",
    "value": "0.75rem",
    "hex": null,
    "note": null
  },
  {
    "name": "--primary",
    "value": "0 95% 40%",
    "hex": "#C70505",
    "note": "#C70505 — button fill, eyebrow labels"
  },
  {
    "name": "--primary-foreground",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": null
  },
  {
    "name": "--accent",
    "value": "0 95% 40%",
    "hex": "#C70505",
    "note": null
  },
  {
    "name": "--accent-foreground",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": null
  },
  {
    "name": "--brand-hover",
    "value": "0 95% 32%",
    "hex": "#9F0404",
    "note": "#9E0404 — darkens on hover (from the DS)"
  },
  {
    "name": "--brand-icon",
    "value": "358 75% 59%",
    "hex": "#E5484D",
    "note": "#E5484D — card icon glyphs"
  },
  {
    "name": "--brand-soft",
    "value": "0 100% 68%",
    "hex": "#FF5C5C",
    "note": "#FF5A5A — decorative borders/glows ONLY"
  },
  {
    "name": "--brand-deep",
    "value": "0 90% 35%",
    "hex": "#AA0909",
    "note": null
  },
  {
    "name": "--selection",
    "value": "0 0% 9%",
    "hex": "#171717",
    "note": null
  },
  {
    "name": "--selection-border",
    "value": "0 0% 25%",
    "hex": "#404040",
    "note": "#404040 — input border on focus"
  },
  {
    "name": "--field",
    "value": "0 0% 83%",
    "hex": "#D4D4D4",
    "note": "#D4D4D4 — input/option border at rest"
  },
  {
    "name": "--field-hover",
    "value": "0 0% 45%",
    "hex": "#737373",
    "note": "#737373 — border on hover"
  },
  {
    "name": "--ring",
    "value": "0 0% 9%",
    "hex": "#171717",
    "note": "focus ring = selection, not red"
  },
  {
    "name": "--error",
    "value": "0 72% 51%",
    "hex": "#DC2828",
    "note": "#DC2626 — 4.83:1 on white ✓ AA"
  },
  {
    "name": "--error-foreground",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": null
  },
  {
    "name": "--destructive",
    "value": "0 72% 51%",
    "hex": "#DC2828",
    "note": "alias so shadcn primitives inherit it"
  },
  {
    "name": "--destructive-foreground",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": null
  },
  {
    "name": "--success",
    "value": "142 72% 29%",
    "hex": "#157F3C",
    "note": "#15803D — 4.86:1 on white ✓ AA"
  },
  {
    "name": "--success-foreground",
    "value": "0 0% 100%",
    "hex": "#FFFFFF",
    "note": null
  },
  {
    "name": "--success-bright",
    "value": "142 71% 45%",
    "hex": "#21C45D",
    "note": "#22C55E — for the dark hero only"
  },
  {
    "name": "--gold",
    "value": "45 97% 50%",
    "hex": "#FBBD04",
    "note": "#FBBC04 — review stars"
  },
  {
    "name": "--whatsapp",
    "value": "142 70% 49%",
    "hex": "#25D466",
    "note": "#25D366"
  },
  {
    "name": "--hero-overlay",
    "value": "linear-gradient(to bottom, rgba(10, 25, 41, 0.6), rgba(13, 27, 42, 0.7), rgba(0, 0, 0, 0.85))",
    "hex": null,
    "note": null
  },
  {
    "name": "--hero-overlay-md",
    "value": "linear-gradient(to bottom, rgba(10, 25, 41, 0.4), rgba(13, 27, 42, 0.5), rgba(0, 0, 0, 0.7))",
    "hex": null,
    "note": null
  },
  {
    "name": "--eq-img-grad",
    "value": "radial-gradient(90% 90% at 50% 20%, #f2f3f6, #e7e9ef)",
    "hex": null,
    "note": null
  },
  {
    "name": "--before-grad",
    "value": "linear-gradient(160deg, #eef0f4, #e2e5ec)",
    "hex": null,
    "note": null
  },
  {
    "name": "--ease-out",
    "value": "cubic-bezier(0.16, 1, 0.3, 1)",
    "hex": null,
    "note": null
  }
];
