/**
 * Reads the real .theme-funnel block out of globals.css and writes it as data
 * for the docs site. The documentation therefore cannot drift from the theme —
 * if a token changes in CSS, re-running this updates the site.
 *
 *   node scripts/extract-tokens.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync("src/app/globals.css", "utf8");
const block = css.slice(css.indexOf(".theme-funnel {"));
const body = block.slice(0, block.indexOf("\n}"));

function hslToHex(h, s, l) {
  s /= 100; l /= 100;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x]
    : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return "#" + [r, g, b].map((v) => Math.round((v + m) * 255).toString(16).padStart(2, "0")).join("").toUpperCase();
}

const tokens = [];
for (const line of body.split("\n")) {
  const m = /^\s*--([a-z0-9-]+):\s*([^;]+);(?:\s*\/\*\s*(.*?)\s*\*\/)?/.exec(line);
  if (!m) continue;
  const [, name, rawValue, note] = m;
  const value = rawValue.trim();
  const hsl = /^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%\s+(\d+(?:\.\d+)?)%$/.exec(value);
  tokens.push({
    name: `--${name}`,
    value,
    hex: hsl ? hslToHex(+hsl[1], +hsl[2], +hsl[3]) : null,
    note: note || null,
  });
}

const out = `// GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
// Source of truth: src/app/globals.css → .theme-funnel
export interface Token { name: string; value: string; hex: string | null; note: string | null }
export const THEME_TOKENS: Token[] = ${JSON.stringify(tokens, null, 2)};
`;
writeFileSync("src/app/(design)/design/_data/tokens.ts", out);
console.log(`✓ ${tokens.length} tokens → src/app/(design)/design/_data/tokens.ts`);
