/**
 * Reads the real token layers out of globals.css and writes them as data for
 * the docs site. The documentation therefore cannot drift from the theme — if a
 * token changes in CSS, re-running this updates the site.
 *
 * Two layers come out:
 *   PRIMITIVES  — the raw ramps in :root (--gray-500, --red-600, …)
 *   THEME_TOKENS — the semantic layer in .theme-funnel, which now mostly points
 *                  at a primitive rather than carrying a value of its own.
 *
 * Semantic tokens are resolved through their var() chain so the docs still show
 * a swatch. `ref` records which primitive a token borrows from, which is the
 * interesting part of the page: it shows the mapping, not just the colour.
 *
 *   node scripts/extract-tokens.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync("src/app/globals.css", "utf8");

function blockOf(selector) {
  const start = css.indexOf(selector);
  if (start === -1) return "";
  const rest = css.slice(start);
  return rest.slice(0, rest.indexOf("\n}"));
}

function hslToHex(h, s, l) {
  s /= 100; l /= 100;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x]
    : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return "#" + [r, g, b].map((v) => Math.round((v + m) * 255).toString(16).padStart(2, "0")).join("").toUpperCase();
}

const HSL = /^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%\s+(\d+(?:\.\d+)?)%$/;
const toHex = (v) => { const m = HSL.exec(v); return m ? hslToHex(+m[1], +m[2], +m[3]) : null; };

/** Every --name: value; in a block, in source order. */
function declarations(body) {
  const out = [];
  for (const line of body.split("\n")) {
    const m = /^\s*--([a-z0-9-]+):\s*([^;]+);(?:\s*\/\*\s*(.*?)\s*\*\/)?/.exec(line);
    if (m) out.push({ name: `--${m[1]}`, value: m[2].trim(), note: m[3] || null });
  }
  return out;
}

const primDecls = declarations(blockOf(":root {"));
const themeDecls = declarations(blockOf(".theme-funnel {"));

const lookup = Object.fromEntries(primDecls.map((d) => [d.name, d.value]));

/**
 * Follow a var() chain to the literal HSL at the end of it. Depth-capped rather
 * than cycle-detected: a loop in a token file is a mistake worth surfacing as a
 * null swatch, not something to paper over.
 */
function resolve(value, depth = 0) {
  const m = /^var\((--[a-z0-9-]+)\)$/.exec(value.trim());
  if (!m) return value;
  if (depth > 6) return value;
  const next = lookup[m[1]];
  return next ? resolve(next, depth + 1) : value;
}

const RAMP = /^--(?:gray|red|coral|green|amber)-\d+$|^--(?:white|slate-50|whatsapp-brand)$/;
const PRIMITIVES = primDecls
  .filter((d) => RAMP.test(d.name) && HSL.test(d.value))
  .map((d) => ({ name: d.name, value: d.value, hex: toHex(d.value), note: d.note }));

const THEME_TOKENS = themeDecls.map((d) => {
  const ref = /^var\((--[a-z0-9-]+)\)$/.exec(d.value)?.[1] ?? null;
  return { name: d.name, value: d.value, ref, hex: toHex(resolve(d.value)), note: d.note };
});

const out = `// GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
// Source of truth: src/app/globals.css
export interface Primitive { name: string; value: string; hex: string | null; note: string | null }
export interface Token { name: string; value: string; ref: string | null; hex: string | null; note: string | null }

/** Tier 1 — the raw ramps in :root. No meaning attached. */
export const PRIMITIVES: Primitive[] = ${JSON.stringify(PRIMITIVES, null, 2)};

/** Tier 2 — the semantic layer in .theme-funnel. \`ref\` names the primitive it borrows. */
export const THEME_TOKENS: Token[] = ${JSON.stringify(THEME_TOKENS, null, 2)};
`;
writeFileSync("src/app/(design)/design/_data/tokens.ts", out);

const linked = THEME_TOKENS.filter((t) => t.ref).length;
const orphan = THEME_TOKENS.filter((t) => !t.hex && !t.value.startsWith("linear-") && !t.value.startsWith("radial-") && !t.value.startsWith("cubic-"));
console.log(`✓ ${PRIMITIVES.length} primitives, ${THEME_TOKENS.length} theme tokens (${linked} pointing at a primitive)`);
if (orphan.length) console.log(`  no swatch for: ${orphan.map((t) => t.name).join(", ")}`);
